
filler_phrases:
  - pattern: "(?:لا بد من القول أن|من الواضح أن|بصفة عامة|بشكل عام|في الحقيقة|بطبيعة الحال)"
    replacements:
      - "وفقًا لبيانات [المصدر] لعام [السنة]،"
      - "تشير النتائج الحديثة إلى أن"
      - "استنادًا إلى تجربة فريق التحرير,"
  - pattern: "(?:يجدر بنا الإشارة إلى|من المؤكد أن|في الواقع)"
    replacements:
      - "تفيد الإحصاءات أن"
      - "عمليًا، تُظهر الأمثلة أن"
style_hints:
  - "ابدأ الفقرة بمعلومة أو رقم أو مصدر."
  - "قلّل العبارات العامة واستبدلها بخبرة مباشرة أو حالة استخدام."
min_confidence: 0.7
