
weights:
  spam_abuse_risk: 0.25
  helpful_content: 0.20
  eeat: 0.15
  trust_compliance: 0.10
  ymyl: 0.05
  cwv_ux: 0.10
  internal_links: 0.07
  duplicate_thin: 0.05
  usefulness_proxy: 0.03

thresholds:
  good: 80
  needs_improve: 60
